config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :members

  
get "signup", to: "users#new"
get "login", to: "sessions#new"
post "login", to: "sessions#create"
delete "logout", to: "sessions#destroy"
resources :users, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
    validates :scoutnummer, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
 
    def logged_in?
        !!current_user
    end
 
    def require_user
        if !logged_in?
            redirect_to login_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index 
    end
    

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index 
        @members = Member.all
    end

    def show
        @members = Member.find(params[:id])
        render json: @members
    end

    def new
        @member = Member.new
    end

    def create
        @member = Member.create(member_params)
        if @member.save
            redirect_to members_path, notice: "Something was successfully created."
            else
            render :new, status: :unprocessable_entity
            end
    end



    private
    def member_params
        params.require(:member).permit(:scoutnummer, :voornaam, :achternaam)
    end


end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
    def new 

    end
    

    def create
        user = User.find_by(username: params[:session][:username].downcase)
        if user && user.authenticate(params[:session][:password_digest])
          session[:user_id] = user.id
          redirect_to root_path
        else
          render 'new'
        end
      end
       
      def destroy
        session[:user_id] = nil
        redirect_to root_path
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          redirect_to root_path
        else
          render 'new'
        end
      end

      def edit
        if !logged_in?
            #send them to login
        else
            #let them use website
        end

      end

        
    
      
     private
      
      def user_params
        params.require(:user).permit(:username, :password_digest)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/scouts_helper.rb
module ScoutsHelper
end

app/views/home/index.html.erb
<h1> Hallo </h1>
<% if logged_in?%>
    <h2>Welcome <%=current_user.username %> </h2>
<% end %>

<%= link_to 'lijst met scouts', members_path() %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scouting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this something from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :scoutnummer %>
    <%= form.text_field :scoutnummer %>
  </div>

  <div class="field">
    <%= form.label :voornaam %>
    <%= form.text_field :voornaam %>
  </div>

  <div class="field">
    <%= form.label :achternaam %>
    <%= form.text_field :achternaam %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/index.html.erb
<h1> Huidige Scouts </h1>

<%= link_to 'nieuwe scout aanmelden', new_member_path() %>


<ul><% @members.each do |member|%> 
    <li>    <%= member.scoutnummer %> &nbsp
        <%= member.voornaam %> &nbsp
        <%= member.achternaam %> &nbsp
<%end%>
</ul>

app/views/members/new.html.erb
<%= render "form", member: @member %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |f| %>
 
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.text_field :username, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.submit %>
</div>
 
<% end %>